services:
  - type: web
    name: Gestion de Inventario
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:O5iRvEiNoSBI+Hk5k9OTd2mcem3h68ZMipQ6dve1dUs=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
